apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  name: flask-docker-k8s-deploy
spec:
  replicas: 4
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: flask-docker-k8s
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  
  template:
    metadata:
      labels:
        app: flask-docker-k8s
    spec:
      volumes:
      - name: pvc-sample
        persistentVolumeClaim:
          claimName: pvc-sample
      containers:
      - name: flask-docker-k8s
        # dockerhub link
        image: mirzakhalov/flask-docker-k8s
        args:
            - --default-ssl-certificate=$(POD_NAMESPACE)/tls-certificate
        resources:
          requests:
            memory: "450Mi"
            cpu: 400m
        ports:
        - containerPort: 5000
        volumeMounts:
        # need to be chosen according to your app needs
        - mountPath: 'var/lib/volume'
          name: pvc-sample
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
