apiVersion: v1
kind: Service
metadata:
  name: flask-docker-k8s-service
  labels:
    app: flask-docker-k8s
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30002
    protocol: TCP
  selector: 
    app: flask-docker-k8s